package io.cortex.ingest.outbox;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Instant;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * End-to-end persistence test for {@link OutboxRepository} against
 * a real Postgres provided by Testcontainers (P4.4a / ADR-0025).
 *
 * <p>Verifies the contracts that H2 cannot exercise:</p>
 * <ul>
 *   <li>V3 Flyway migration applies cleanly (the Spring context
 *       boots, which means {@code outbox_events} exists and the
 *       repository CRUD targets the right schema).</li>
 *   <li>{@code CHECK (status IN ('PENDING','PUBLISHED','FAILED'))}
 *       accepts the three documented values.</li>
 *   <li>{@code id} is server-side generated by the
 *       {@code BIGSERIAL} sequence (insert returns a non-null id;
 *       null id forces an INSERT, not an UPDATE).</li>
 *   <li>The PENDING -&gt; PUBLISHED lifecycle transition is
 *       persistable (the P4.4b poller will mutate {@code status}
 *       in place).</li>
 * </ul>
 *
 * <p>Named {@code *IT} so Failsafe runs it; Surefire ignores it.</p>
 */
@SpringBootTest
@Testcontainers
class OutboxRepositoryIT {

    /** Shared Postgres 16 container; reused across all test methods. */
    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres =
            new PostgreSQLContainer<>("postgres:16-alpine");

    /** Production repository under test. */
    @Autowired private OutboxRepository repository;

    /** Default constructor used by JUnit. */
    OutboxRepositoryIT() {
        // no state
    }

    /**
     * Inserts a PENDING row and verifies the BIGSERIAL id is
     * assigned, all columns roundtrip, and findById reloads the
     * same payload.
     */
    @Test
    void insertsPendingRowAndAssignsBigserialId() {
        final OutboxEvent fresh = OutboxEvent.pending(
                "cortex-dev",
                "evt-it-pending-1",
                "{\"eventId\":\"evt-it-pending-1\"}",
                Instant.parse("2026-06-02T10:00:00Z"));

        final OutboxEvent saved = this.repository.save(fresh);

        assertThat(saved.id()).isNotNull().isPositive();
        final OutboxEvent reloaded = this.repository.findById(saved.id()).orElseThrow();
        assertThat(reloaded.tenantId()).isEqualTo("cortex-dev");
        assertThat(reloaded.eventId()).isEqualTo("evt-it-pending-1");
        assertThat(reloaded.payload()).isEqualTo("{\"eventId\":\"evt-it-pending-1\"}");
        assertThat(reloaded.status()).isEqualTo(OutboxStatus.PENDING.name());
        assertThat(reloaded.attempts()).isZero();
        assertThat(reloaded.nextAttemptAt()).isNotNull();
        assertThat(reloaded.createdAt()).isNotNull();
        assertThat(reloaded.publishedAt()).isNull();
        assertThat(reloaded.lastError()).isNull();
    }

    /**
     * Simulates the P4.4b poller success path: load a PENDING row,
     * stamp {@code status = PUBLISHED} and {@code published_at},
     * save the rebuilt aggregate, reload and verify the new state
     * sticks.
     */
    @Test
    void pendingRowCanTransitionToPublished() {
        final OutboxEvent saved = this.repository.save(OutboxEvent.pending(
                "cortex-dev",
                "evt-it-published-1",
                "{}",
                Instant.parse("2026-06-02T10:01:00Z")));

        final Instant publishedAt = Instant.parse("2026-06-02T10:02:00Z");
        final OutboxEvent published = new OutboxEvent(
                saved.id(),
                saved.tenantId(),
                saved.eventId(),
                saved.payload(),
                OutboxStatus.PUBLISHED.name(),
                saved.attempts(),
                saved.nextAttemptAt(),
                saved.lastError(),
                saved.createdAt(),
                publishedAt);
        this.repository.save(published);

        final OutboxEvent reloaded = this.repository.findById(saved.id()).orElseThrow();
        assertThat(reloaded.status()).isEqualTo(OutboxStatus.PUBLISHED.name());
        assertThat(reloaded.publishedAt()).isEqualTo(publishedAt);
    }

    /**
     * Simulates the P4.4c failure path: load a PENDING row, stamp
     * {@code status = FAILED}, increment {@code attempts}, capture
     * {@code last_error}, save, reload and verify.
     */
    @Test
    void pendingRowCanTransitionToFailedWithDiagnostics() {
        final OutboxEvent saved = this.repository.save(OutboxEvent.pending(
                "cortex-dev",
                "evt-it-failed-1",
                "{}",
                Instant.parse("2026-06-02T10:03:00Z")));

        final OutboxEvent failed = new OutboxEvent(
                saved.id(),
                saved.tenantId(),
                saved.eventId(),
                saved.payload(),
                OutboxStatus.FAILED.name(),
                3,
                saved.nextAttemptAt(),
                "BinderException: broker unavailable",
                saved.createdAt(),
                null);
        this.repository.save(failed);

        final OutboxEvent reloaded = this.repository.findById(saved.id()).orElseThrow();
        assertThat(reloaded.status()).isEqualTo(OutboxStatus.FAILED.name());
        assertThat(reloaded.attempts()).isEqualTo(3);
        assertThat(reloaded.lastError()).isEqualTo("BinderException: broker unavailable");
        assertThat(reloaded.publishedAt()).isNull();
    }
}
