apiVersion: 1

datasources:
  - name: Cortex Prometheus
    uid: cortex-prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      queryTimeout: 30s
      httpMethod: POST

